import { Tender } from "@/types";

export const tenders: Tender[] = [
    {
        "id": "tender-900012-2025-0",
        "uasg": "122456",
        "number": "900012/2025",
        "description": "Aqs Ração Canina (1) e Equina (2)",
        "department": "9º B Sup",
        "openingDate": "2026-01-01T09:00:00",
        "status": "completed",
        "currentStage": "Edital Publicado",
        "hasIssues": false,
        "isGCALC": true,
        "coord": "CCOL",
        "responsibleInternal": "",
        "responsibleExternal": "S Ten L Alves",
        "biPublication": "",
        "intercurrences": "Requisitória foi protocolada X dias após o prazo",
        "optimizationNotes": "Nada sobre nosso alcance para redução, só fechar a decisão do pregoeiro e do OD, só tá amarrado a prazo legal e priorização",
        "nextDeadline": "Sem prazo\nHomologado",
        "nextActivity": "1. Entrada do TR na SAL",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-90013-2025-1",
        "uasg": "122456",
        "number": "90013/2025",
        "description": "Contratação de serviços - PASA",
        "department": "18º B Trnp",
        "openingDate": "2026-01-09T09:00:00",
        "status": "suspended",
        "currentStage": "Homologação",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CAF",
        "responsibleInternal": "S Ten L Alves",
        "responsibleExternal": "3º Sgt Caldeira",
        "biPublication": "BI nº4/ 2026",
        "intercurrences": "Anteriormente estava com o Sgt Lobo como pregoeiro, agora está com o STen L Alves que está em acúmulo com outros 11 processos",
        "optimizationNotes": "Linha de ação: Alves vai analisar DE NOITE, corrigir itens da IRP, pegar assinaturas e republicar na EBC e no comprasnet",
        "nextDeadline": "25/02/2026",
        "nextActivity": "8 Adjudicação e Homologação",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-90014-2025-2",
        "uasg": "122456",
        "number": "90014/2025",
        "description": "Aqs Pç Mnt Vtr - AUDATEX",
        "department": "9º B Mnt",
        "openingDate": "2025-12-29T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CCOL",
        "responsibleInternal": "S Ten Cunha",
        "responsibleExternal": "2º Sgt Octávio",
        "biPublication": "PREGOEIRO FAVOR CONFERIR  A PUBLICAÇÃO EM BI, SE ESTIVER PUBLICADO",
        "intercurrences": "Ficou mais de um mês em correção no setor requisitante após parecer jurídico",
        "optimizationNotes": "Já tá tá encaminhado para publicação, já tem data, só esperar a seção publica chegar e operar",
        "nextDeadline": "Sem prazo\nHomologado",
        "nextActivity": "8 Adjudicação e Homologação",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-90017-2025-3",
        "uasg": "122456",
        "number": "90017/2025",
        "description": "Aquisição de material permanente - PASA",
        "department": "18º B Trnp",
        "openingDate": "2025-12-26T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CAF",
        "responsibleInternal": "2º Sgt Octávio",
        "responsibleExternal": "3º Sgt Carvalho",
        "biPublication": "PREGOEIRO FAVOR CONFERIR  A PUBLICAÇÃO EM BI, SE ESTIVER PUBLICADO",
        "intercurrences": "vide coluna Obs.",
        "optimizationNotes": "Encaminhado para ser publicado no dia 12, não tem o que possa fazer para reduzir prazo.",
        "nextDeadline": "09/02/2026",
        "nextActivity": "8 Adjudicação e Homologação",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-90023-2025-4",
        "uasg": "122456",
        "number": "90023/2025",
        "description": "Aquisição de material de consumo - PASA",
        "department": "18º B Trnp",
        "openingDate": "2025-12-26T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CAF",
        "responsibleInternal": "S Ten L Alves",
        "responsibleExternal": "2º Sgt Octávio",
        "biPublication": "PREGOEIRO FAVOR CONFERIR  A PUBLICAÇÃO EM BI, SE ESTIVER PUBLICADO",
        "intercurrences": "",
        "optimizationNotes": "Encaminhado para ser publicado no dia 12, não tem o que possa fazer para reduzir prazo.",
        "nextDeadline": "Sem prazo\nHomologado",
        "nextActivity": "8 Adjudicação e Homologação",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-90018-2025-5",
        "uasg": "122456",
        "number": "90018/2025",
        "description": "Aqs de material de saúde (medicamentos e odonto) - Classe VIII",
        "department": "9º B Sup",
        "openingDate": "2026-01-26T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "S Ten L Alves",
        "responsibleExternal": "S Ten Cunha",
        "biPublication": "",
        "intercurrences": "vide coluna Obs.",
        "optimizationNotes": "",
        "nextDeadline": "06/03/2026",
        "nextActivity": "8 Adjudicação e Homologação",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-90021-2025-6",
        "uasg": "122456",
        "number": "90021/2025",
        "description": "Aqs QS 1ª Provisão 2026",
        "department": "9º B Sup",
        "openingDate": "2026-01-08T09:00:00",
        "status": "completed",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CCOL",
        "responsibleInternal": "S Ten Cunha",
        "responsibleExternal": "S Ten L Alves",
        "biPublication": "BI nr 157, de 27/08/25",
        "intercurrences": "vide coluna Obs.",
        "optimizationNotes": "",
        "nextDeadline": "Sem prazo\nHomologado",
        "nextActivity": "7.2 Resposta a Recurso",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-90001-2026-7",
        "uasg": "122456",
        "number": "90001/2026",
        "description": "Aqs Material Elétrico 2026",
        "department": "Cmdo 9º Gpt",
        "openingDate": "2026-04-30T09:00:00",
        "status": "completed",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CAF",
        "responsibleInternal": "3º Sgt Belarmino",
        "responsibleExternal": "3º Sgt Dainy",
        "biPublication": "BELARMINO FAVOR RETIFICAR PUBLICAÇÃO DESTE E DO PREGÃO DO CARVALHO",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "28/02/2026",
        "nextActivity": "3. Envio para CJU",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-001-2025-8",
        "uasg": "122456",
        "number": "001/2025",
        "description": "Leilão (Alienação de Cl IX)",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "S Ten L Alves",
        "responsibleExternal": "Leiloeiro",
        "biPublication": "MARCO FAVOR CONSTAR AQUI A PUBLICAÇAO RESPECTIVA, FALAR COM O ALVES POR FAVOR",
        "intercurrences": "Embaraçado pela falta de definição de responsabilidade do parecer entre CONJUR e AGU",
        "optimizationNotes": "",
        "nextDeadline": "Sem prazo",
        "nextActivity": "4.1 Regresso da CONJUR",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-002-2025-9",
        "uasg": "122456",
        "number": "002/2025",
        "description": "Leilão (Alienação de Cl VI) 65345.004465/2025-41",
        "department": "9º B Mnt",
        "openingDate": "2026-02-15T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "S Ten L Alves",
        "responsibleExternal": "Leiloeiro",
        "biPublication": "MARCO FAVOR CONSTAR AQUI A PUBLICAÇAO RESPECTIVA, FALAR COM O ALVES POR FAVOR",
        "intercurrences": "Embaraçado pela falta de definição de responsabilidade do parecer entre CONJUR e AGU",
        "optimizationNotes": "Ou adiar a prioridade, ou trazer Castelo, ou Fabio Silva, ou Regis, e simultaneamente incentivar a OM de origem. Solicitar apoio do Ojeda pela experiencia com leilão.",
        "nextDeadline": "30/01/2026",
        "nextActivity": "5. Ajuste para publicação na OMDS",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-10",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aqs de Pçs Mnt de Vtr Bld (Classe IX) NUP: 65345.000650/2025-66 \n(apelido \"pregão de dois mil itens\")",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "",
        "responsibleExternal": "Fabio Silva",
        "biPublication": "",
        "intercurrences": "A previsão de início da fase pública ERA 23/09/2025, mas foi prejudicada pelo tempo de retificação pela OMDS após o parecer (Alves confirmar)",
        "optimizationNotes": "Morreu pela manobra. Verificar com o Cmt BMNT se pode ser apagado",
        "nextDeadline": "15/01/2026",
        "nextActivity": "5. Ajuste para publicação na OMDS",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-11",
        "uasg": "122456",
        "number": "A definir",
        "description": "Sv Mnt Vtr Bld (Classe IX) NUP 65345.005212/2024-11",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "A definir",
        "biPublication": "",
        "intercurrences": "o Prazo de início da fase pública ERA 27/08/2025. O prazo de retorno do edital após correções seria 15/08, mas não ocorreu",
        "optimizationNotes": "Morreu pela manobra. Verificar com o Cmt BMNT se pode ser apagado",
        "nextDeadline": "Abandonado",
        "nextActivity": "9 Abandonado",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-12",
        "uasg": "122456",
        "number": "A definir",
        "description": "Sv de instalação de ponte rolante com Cap 20 Ton (Pel Mnt Vtr Bld) 65345.000226/2026-01",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "3º Sgt Carvalho",
        "responsibleExternal": "2º Sgt Octávio",
        "biPublication": "BI Nr 23, de 4 Fev 26",
        "intercurrences": "Fase Int\r\nSt Req (OM info prev de envio em 30/08, não ocorreu)",
        "optimizationNotes": "Morreu pela manobra. Verificar com o Cmt BMNT se pode ser apagado",
        "nextDeadline": "30/01/2026",
        "nextActivity": "1.1 Solicitação de PRO pelo Set Req",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-13",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aqs de cabine de pintura para a Seção de Lanternagem e Pintura 65345.000227/2026-47",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "3º Sgt Caldeira",
        "responsibleExternal": "3º Sgt Carvalho",
        "biPublication": "BI Nr 23, de 4 Fev 26",
        "intercurrences": "30/05/25 (Solicitado pela OM adiar o prazo que era 31/03/25)",
        "optimizationNotes": "Morreu pela manobra. Verificar com o Cmt BMNT se pode ser apagado",
        "nextDeadline": "15/02/2026",
        "nextActivity": "1. Entrada do TR pelo Set Req",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-90022-2025-14",
        "uasg": "122456",
        "number": "90022/2025",
        "description": "Aqs de insumos para oficinas (Armamento, correaria, carpintaria, tornearia, Lanternagem e pintura)",
        "department": "9º B Mnt",
        "openingDate": "2026-01-30T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "S Ten Cunha",
        "responsibleExternal": "A definir",
        "biPublication": "",
        "intercurrences": "Retornou em 25/11/2025. Estava indicando marca, planeja-se retomar as correções após as férias do S Ten Cunha. Está antecipado",
        "optimizationNotes": "Definir se vai priorizar ou não. Definir pregoeiro quando chegarem ou usar os nomes acima propostos - Castelo vai fazer",
        "nextDeadline": "15/01/2026",
        "nextActivity": "6. Publicação do Aviso de Licitação",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-90016-2025-15",
        "uasg": "122456",
        "number": "90016/2025",
        "description": "Aqs de insumos Cl IX Baterias e Óleos",
        "department": "9º B Mnt",
        "openingDate": "2025-12-11T09:00:00",
        "status": "completed",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "S Ten Cunha",
        "responsibleExternal": "S Ten L Alves",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "Já tá em operação, hoje abriu a seção pública",
        "nextDeadline": "Sem prazo\nHomologado",
        "nextActivity": "8 Adjudicação e Homologação",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-16",
        "uasg": "122456",
        "number": "A definir",
        "description": "Sv Mnt Vtr Bld (Classe IX) NUP 65345.003175/2025-80",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "2º Sgt Lobo (desligado)",
        "responsibleExternal": "A definir",
        "biPublication": "",
        "intercurrences": "Novo prazo seria 29/09/25 (Sol prazo p/ 03/11/25, através  DIEx nº 2108-Fisc Adm/9º B Mnt, de 9/10/25)",
        "optimizationNotes": "Depende da OM de origem",
        "nextDeadline": "28/02/2026",
        "nextActivity": "5. Ajuste para publicação na OMDS",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-90024-2025-17",
        "uasg": "122456",
        "number": "90024/2025",
        "description": "Sv Mnt Mat Eng (Classe VI) - NUP 65345.005019/2025-53",
        "department": "9º B Mnt",
        "openingDate": "2026-02-26T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "3º Sgt Caldeira",
        "responsibleExternal": "3º Sgt Carvalho",
        "biPublication": "BI nº242/ 2025",
        "intercurrences": "Novo prazo seria 29/09/25 (Sol prazo p/ 03/11/25, através  DIEx nº 2108-Fisc Adm/9º B Mnt, de 9/10/25)",
        "optimizationNotes": "Depende da OM de origem",
        "nextDeadline": "16/2/26",
        "nextActivity": "5.1 Ajuste para publicação na SAL",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-18",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aqs de insumos e pç para Mnt Mat Eng",
        "department": "9º B Mnt",
        "openingDate": "2026-08-10T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "A definir",
        "biPublication": "",
        "intercurrences": "-",
        "optimizationNotes": "",
        "nextDeadline": "15/04/2026",
        "nextActivity": "1. Entrada do TR pelo Set Req",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender---19",
        "uasg": "122456",
        "number": "-",
        "description": "Aquisição de QR - GLP (2026) - 2ª Licitação",
        "department": "9º B Sup",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "9º B Sup",
        "responsibleInternal": "",
        "responsibleExternal": "A cargo do 9º B Sup",
        "biPublication": "",
        "intercurrences": "-",
        "optimizationNotes": "",
        "nextDeadline": "A cargo do 9º B Sup",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-90001-2026-20",
        "uasg": "122456",
        "number": "90001/2026",
        "description": "Aquisição de QR - Padaria",
        "department": "9º B Sup",
        "openingDate": "2026-02-24T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "9º B Sup",
        "responsibleInternal": "",
        "responsibleExternal": "A cargo do 9º B Sup",
        "biPublication": "",
        "intercurrences": "-",
        "optimizationNotes": "",
        "nextDeadline": "A cargo do 9º B Sup",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-90002-2026-21",
        "uasg": "122456",
        "number": "90002/2026",
        "description": "Aquisição de QR - Hortifruti - 2ª Licitação",
        "department": "9º B Sup",
        "openingDate": "2026-03-02T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "9º B Sup",
        "responsibleInternal": "",
        "responsibleExternal": "A cargo do 9º B Sup",
        "biPublication": "",
        "intercurrences": "-",
        "optimizationNotes": "",
        "nextDeadline": "A cargo do 9º B Sup",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-90003-2026-22",
        "uasg": "122456",
        "number": "90003/2026",
        "description": "Aquisição de QR - Enalatados e Embutidos - 2ª Licitação",
        "department": "9º B Sup",
        "openingDate": "2026-03-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "9º B Sup",
        "responsibleInternal": "",
        "responsibleExternal": "A cargo do 9º B Sup",
        "biPublication": "",
        "intercurrences": "mais 4 meses de prorrogação",
        "optimizationNotes": "",
        "nextDeadline": "A cargo do 9º B Sup",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender---23",
        "uasg": "122456",
        "number": "-",
        "description": "Sv Mnt Prev e Corr Câmaras Frigoríficas",
        "department": "9º B Sup",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "9º B Sup",
        "responsibleInternal": "",
        "responsibleExternal": "A cargo do 9º B Sup",
        "biPublication": "",
        "intercurrences": "mais 4 meses de prorrogação",
        "optimizationNotes": "",
        "nextDeadline": "A cargo do 9º B Sup",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender---24",
        "uasg": "122456",
        "number": "-",
        "description": "Aquisição de QR - Chamada Pública",
        "department": "9º B Sup",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "9º B Sup",
        "responsibleInternal": "",
        "responsibleExternal": "A cargo do 9º B Sup",
        "biPublication": "",
        "intercurrences": "Termo aditivo até 4/4",
        "optimizationNotes": "",
        "nextDeadline": "A cargo do 9º B Sup",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-25",
        "uasg": "122456",
        "number": "A definir",
        "description": "Chamada pública da Coleta Seletiva",
        "department": "Cmdo 9º Gpt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CAF",
        "responsibleInternal": "3º Sgt Dainy",
        "responsibleExternal": "3º Sgt Dainy",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "Depende da OM de origem",
        "nextDeadline": "16/2",
        "nextActivity": "3. Envio para CJU",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-26",
        "uasg": "122456",
        "number": "A definir",
        "description": "Telhado da Cia de Transporte do 18º B Trnp NUP 64136.003328/2025-91",
        "department": "18º B Trnp",
        "openingDate": "2026-04-30T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CAF",
        "responsibleInternal": "3º Sgt Belarmino",
        "responsibleExternal": "S Ten L Alves",
        "biPublication": "",
        "intercurrences": "PDRMDEC chegou informando que vai vir 900 mil",
        "optimizationNotes": "Dependerá da OM de origem",
        "nextDeadline": "15/2/2026",
        "nextActivity": "3. Envio para CJU",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-27",
        "uasg": "122456",
        "number": "A definir",
        "description": "Sv Mnt Vtr Não-Blindadas NUP 65345.005020/2025-88",
        "department": "9º B Mnt",
        "openingDate": "2026-02-26T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "3º Sgt Carvalho",
        "responsibleExternal": "3º Sgt Caldeira",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "28/02/2026",
        "nextActivity": "1. Entrada do TR pelo Set Req",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-28",
        "uasg": "122456",
        "number": "A definir",
        "description": "Inexigibilidade TUSD (Energia Elétrica) NUP 65297.014405/2025-59",
        "department": "Cmdo 9º Gpt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CAF",
        "responsibleInternal": "3º Sgt Reinaldo",
        "responsibleExternal": "3º Sgt Reinaldo",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "27/2/2026",
        "nextActivity": "7. Fase  Externa",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-29",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de QS",
        "department": "9º B Sup",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "23/8/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-30",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de material de consumo - PASA",
        "department": "18º B Trnp",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CAF",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "15/8/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-31",
        "uasg": "122456",
        "number": "A definir",
        "description": "Contratação de serviços - PASA",
        "department": "18º B Trnp",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CAF",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "15/8/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-32",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de material permanente - PASA",
        "department": "18º B Trnp",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CAF",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "23/8/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-33",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de ração canina (1) e equina (2), alfafa, aveia e feno",
        "department": "9º B Sup",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "5/8/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-34",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de peças de Vtr - AUDATEX",
        "department": "9º B Sup",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "22/06/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-35",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de QR Enlatados e Embutidos",
        "department": "9º B Sup",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CAF",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "A ser definido conforme prazo da vigência do atual certame que está por ser homologado pelo 9 BSUP. A data de deadline para protocolo do novo certame será 4 meses antes do término da vigência do novo pregão",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-36",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de colchões, armários, beliches, cama, mesa e banho.",
        "department": "9º B Sup",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "9º B Sup",
        "responsibleInternal": "A Cargo do 9 BSUP",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "A Cargo do 9 BSUP",
        "optimizationNotes": "",
        "nextDeadline": "A cargo do 9º B Sup",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-37",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de Material Elétrico",
        "department": "9º B Sup",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "9º B Sup",
        "responsibleInternal": "A Cargo do 9 BSUP",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "A Cargo do 9 BSUP",
        "optimizationNotes": "",
        "nextDeadline": "A cargo do 9º B Sup",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-38",
        "uasg": "122456",
        "number": "A definir",
        "description": "Uniformes especiais e históricos, bandeiras e insígnias",
        "department": "9º B Sup",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "9º B Sup",
        "responsibleInternal": "A Cargo do 9 BSUP",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "A Cargo do 9 BSUP",
        "optimizationNotes": "",
        "nextDeadline": "A cargo do 9º B Sup",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-39",
        "uasg": "122456",
        "number": "A definir",
        "description": "Contratação de serviços de manutenção preventiva e corretiva de câmaras frigoríficas",
        "department": "9º B Sup",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "9º B Sup",
        "responsibleInternal": "A Cargo do 9 BSUP",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "A Cargo do 9 BSUP",
        "optimizationNotes": "",
        "nextDeadline": "A cargo do 9º B Sup",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-40",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de QR - Chamada pública",
        "department": "9º B Sup",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "9º B Sup",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "A cargo do 9º B Sup",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-41",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de gorro de selva",
        "department": "9º B Sup",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "9º B Sup",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "A cargo do 9º B Sup",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-42",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de peças para manutenção de material de engenharia - Embarcações, motores de popa e geradores (Classe VI)",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "13/06/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-43",
        "uasg": "122456",
        "number": "A definir",
        "description": "Contratação de serviços de manutenção de Vtr Bld - Serviços não continuados (Classe IX)",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "Controle duplicado (licitação igual em A-1 ainda não concluída)",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-44",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de geradores e equipamentos de ar condicionados - H Cmp",
        "department": "9º B Sau",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CAF",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "15/02/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-45",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de insumos Classe IX - Baterias, óleos, filtros e graxas",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "24/01/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-46",
        "uasg": "122456",
        "number": "A definir",
        "description": "Contratação de serviços Mnt de Vtr - AUDATEX (Classe IX)",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "05/03/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-47",
        "uasg": "122456",
        "number": "A definir",
        "description": "Contratação de serviços de análise e tratamento de água - poços artesianos do Forte Logístico - 5 meses (Dispensa de Licitação)",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CAF",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "06/03/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-48",
        "uasg": "122456",
        "number": "A definir",
        "description": "Contratação de serviço de coleta de resíduo hospitalar \n(Dispensa de licitação)",
        "department": "9º B Sup",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CAF",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "22/03/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-49",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de ferramental para oficinas e máquina de costura para correaria",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "08/05/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-50",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de QS - Chamada Pública",
        "department": "9º B Sup",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "19/05/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-51",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de peças para manutenção de viaturas blindadas (Classe IX)",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "Controle duplicado (licitação igual em A-1 ainda não concluída)",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-52",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de cabine de pintura para a Seção de Lanternagem e Pintura",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CCOL",
        "responsibleInternal": "3º Sgt Caldeira",
        "responsibleExternal": "3º Sgt Carvalho",
        "biPublication": "Previsão BI Nr 23, de 4 Fev 26.",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "22/02/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-53",
        "uasg": "122456",
        "number": "A definir",
        "description": "Serviço de instalação de ponte rolante com capacidade de 20 Ton para adequação do Pel Mnt Vtr Bld",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "11/03/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-54",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de insumos Classe IX – Pneus",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "19/07/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-55",
        "uasg": "122456",
        "number": "A definir",
        "description": "Alienação de bens móveis – Leilão (Classe VI)",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "09/04/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-56",
        "uasg": "122456",
        "number": "A definir",
        "description": "Alienação de bens móveis – Leilão (Classe IX)",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "10/04/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-57",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de insumos para oficinas (armamento, correaria, carpintaria, tornearia e lanternagem e pintura)",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "08/05/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-58",
        "uasg": "122456",
        "number": "A definir",
        "description": "Contratação de serviços para manutenção de material de engenharia - Embarcações, motores de popa e geradores (Classe VI)",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "Controle duplicado (licitação igual em A-1 ainda não concluída)",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-59",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de peças para manutenção de material de engenharia - Embarcações, motores de popa e geradores (Classe VI)",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "13/06/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-60",
        "uasg": "122456",
        "number": "A definir",
        "description": "Contratação de serviços de manutenção de Vtr Bld - Serviços não continuados (Classe IX)",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "24/09/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-61",
        "uasg": "122456",
        "number": "A definir",
        "description": "Contratação de Leiloeiro",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CAF",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "10/09/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-62",
        "uasg": "122456",
        "number": "A definir",
        "description": "Cessão de uso de imóvel para funcionamento de Serviços Financeiros",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CAF",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "10/03/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-63",
        "uasg": "122456",
        "number": "A definir",
        "description": "Cessão de uso de imóvel para funcionamento de Cantina",
        "department": "18º B Trnp",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CAF",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "25/05/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-64",
        "uasg": "122456",
        "number": "A definir",
        "description": "Serviço de Internet dados móveis",
        "department": "18º B Trnp",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CAF",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "11/01/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-65",
        "uasg": "122456",
        "number": "A definir",
        "description": "Contratação de serviço para reforma/substituição da rede interna de esgoto do 18º B Trnp",
        "department": "18º B Trnp",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CAF",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "Cfm PRO",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-66",
        "uasg": "122456",
        "number": "A definir",
        "description": "Cl IX- aquisição de viatura para o Centro de Formação de Motorista Militar (CFMM)  64136.000261/2026-14",
        "department": "18º B Trnp",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "A definir",
        "responsibleInternal": "2º Sgt Octávio",
        "responsibleExternal": "3º Sgt Carvalho",
        "biPublication": "BI Nr 22, de 3 Fev 26",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "12/2/2026",
        "nextActivity": "1. Entrada do TR pelo Set Req",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-67",
        "uasg": "122456",
        "number": "A definir",
        "description": "Solicitação : 202209000179 - Reparação / Alvenaria / Reserva de Material\nReserva de Material / Reserva de Material, DEF e Permissionário / 18º B\nTrnp  (DISPENSA ELETRÔNICA R$ 15.685,63)",
        "department": "Cia C",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "Cia C",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "17/1/2026",
        "nextActivity": "0. DIEx com alerta de prazo para OMDS 5 dias antes",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-68",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de peças para PALL",
        "department": "18º B Trnp",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-69",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de peças para PALL",
        "department": "18º B Trnp",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-70",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de Serviço para manutenção de PALL",
        "department": "18º B Trnp",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-71",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de Pneus para viaturas blindadas e não-blindadas",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-72",
        "uasg": "122456",
        "number": "A definir",
        "description": "OLG (óleos, graxas, lubrificantes e ARLA) e afins para viaturas Bld, nãoBlindadas, Armamento, Motocicletas e Material de Engenharia (Embarcações eEquipamentos de Eng)",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-73",
        "uasg": "122456",
        "number": "A definir",
        "description": "Baterias para Vtr Bld, não Blindada, Motocicleta, embarcações, geradores eEquipamento de Engenharia.",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-74",
        "uasg": "122456",
        "number": "A definir",
        "description": "Tintas e afins para Vtr blindadas, não blindadas, armamentos, embarcações,geradores e Equipamento de Eng",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "A definir",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-75",
        "uasg": "122456",
        "number": "A definir",
        "description": "Serviços de viaturas não blindada e motocicleta das seguintes marcas: (Honda,Yamaha, MBB - ônibus/caminhões, Volkswagen - Caminhões/ônibus, Agrale, Toyota, Nissan, Mitsubishi, Renaut - Ambulâncias/Van, Iveco - CavMec/caminhões/Van, Scania - Cav Mec, Volvo - Cav Mec/Caminhões/ônibus, DAF- CavMec)",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-76",
        "uasg": "122456",
        "number": "A definir",
        "description": "Peças de viaturas não blindada e motocicleta das seguintes marcas: (Honda,Yamaha, MBB - ônibus/caminhões, Volkswagen - Caminhões/ônibus, Agrale, Toyota, Nissan, Mitsubishi, Renaut - Ambulâncias/Van, Iveco - CavMec/caminhões/Van, Scania - Cav Mec, Volvo - Cav Mec/Caminhões/ônibus, DAF- CavMec)",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-TBD-77",
        "uasg": "122456",
        "number": "A definir",
        "description": "Peças de viaturas blindadas: Cascavel; Guarani; M60 A3TTS e M113BR",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-TBD-78",
        "uasg": "122456",
        "number": "A definir",
        "description": "Serviços de viatura blindadas: Cascavel; Guarani; M60 A3TTS e M113BR",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-TBD-79",
        "uasg": "122456",
        "number": "A definir",
        "description": "Peças e Serviço de manutenção em VSRE Prancha e VSRNE Graneleiro",
        "department": "18º B Trnp",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-TBD-80",
        "uasg": "122456",
        "number": "A definir",
        "description": "Peças e Serviço de manutenção em VTE Frigorífico, VSRE Frigorífico, ContainerFrigorífico.",
        "department": "18º B Trnp",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-TBD-81",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aluguel de VTE para salvamento e evacuação: VSRE Pranchas e VTTNE CavaloMecânico, VTE Socorro Leve e Pesado",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-TBD-82",
        "uasg": "122456",
        "number": "A definir",
        "description": "Pregão de Insumos para oficinas (Latão, bronze, ferro redondo e tarugo, lixas de váriasgranulometrias, buchas mecânicas em geral, madeiras em geral, compensado naval,courvin, napa, lona encerada e tecidos para capotaria, metalão, ferro chato, canteirasdiversas, pregos, parafusos diversos, lixas em geral, cabos de aços revestidos emgeral, dobradiças, aldrabas, grampos de aços diversos e lacres com cabo de açonumerado diversos",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-TBD-83",
        "uasg": "122456",
        "number": "A definir",
        "description": "Pregão de ferramental, materiais permanentes, paletes plásticos e metálicos, canastrapara transporte de armamento, paleteiras, máquina de embalagem para arquear fitaplástica e metálica",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-TBD-84",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de container não refrigerado de 20 e 40 pés para transporte earmazenamento de material e container de 20 e 40 Pés para armazenamento etransporte de material Cl III (OLG), V (Armt) e IX (Moto e Bld)",
        "department": "9º B Sup",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-TBD-85",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de Peças e Serviços de manutenção de geradores",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-TBD-86",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de Peças e Serviços de manutenção de embarcações",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-TBD-87",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de Peças e Serviços de manutenção de equipamentos de outrasClasses: Cl X",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CCOL",
        "responsibleInternal": "",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-88",
        "uasg": "122456",
        "number": "A definir",
        "description": "Aquisição de acessórios, insumos epeças para\n manutenção de viaturas não blindadas do Comando Militar do Oeste - 2026.2.\nAqs Pç Mnt Vtr - AUDATEX (\"Preguinho\") 65345.000068/2026-81",
        "department": "9º B Mnt",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": true,
        "coord": "CCOL",
        "responsibleInternal": "S Ten Cunha",
        "responsibleExternal": "2º Sgt Octávio",
        "biPublication": "BI Nr 8, de 14/01/2026",
        "intercurrences": "Pregão oriundo da instabilidade no comprasnet em 29 DEZ, foram perdidos entre 10 e 20 itens",
        "optimizationNotes": "Já tá tá encaminhado para publicação, já tem data, só esperar a seção publica chegar e operar",
        "nextDeadline": "09/01/2026",
        "nextActivity": "1. Entrada do TR pelo Set Req",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender---89",
        "uasg": "122456",
        "number": "-",
        "description": "Chamada Pública Agricultura  Familiar QR",
        "department": "9º B Sup",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": false,
        "isGCALC": true,
        "coord": "9º B Sup",
        "responsibleInternal": "",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-90013-25-90",
        "uasg": "122456",
        "number": "90013/25",
        "description": "Contratação de Sv de Mat Instalações e Mnt Equipamentos",
        "department": "9º B Sup",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": false,
        "isGCALC": false,
        "coord": "9º B Sup",
        "responsibleInternal": "",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-90014-25-91",
        "uasg": "122456",
        "number": "90014/25",
        "description": "Aqs Mat Consumo",
        "department": "9º B Sup",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": false,
        "isGCALC": false,
        "coord": "9º B Sup",
        "responsibleInternal": "",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-90015-25-92",
        "uasg": "122456",
        "number": "90015/25",
        "description": "Aquisição de Material Permanente",
        "department": "9º B Sup",
        "openingDate": "2025-12-15T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": false,
        "isGCALC": false,
        "coord": "9º B Sup",
        "responsibleInternal": "",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-90016-25-93",
        "uasg": "122456",
        "number": "90016/25",
        "description": "Aqs Material de Engenharia e Cartografia",
        "department": "9º B Sup",
        "openingDate": "2025-12-15T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": false,
        "isGCALC": false,
        "coord": "9º B Sup",
        "responsibleInternal": "",
        "responsibleExternal": "",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "",
        "nextActivity": "",
        "updates": [],
        "observations": []
    },
    {
        "id": "tender-A-definir-94",
        "uasg": "122456",
        "number": "A definir",
        "description": "Contratação do Projeto Soldado Cidadão",
        "department": "18º B Trnp",
        "openingDate": "2026-01-01T09:00:00",
        "status": "active",
        "currentStage": "Edital Publicado",
        "hasIssues": true,
        "isGCALC": false,
        "coord": "CAF",
        "responsibleInternal": "A definir",
        "responsibleExternal": "A definir",
        "biPublication": "",
        "intercurrences": "",
        "optimizationNotes": "",
        "nextDeadline": "",
        "nextActivity": "",
        "updates": [],
        "observations": []
    }
];
